name: Frontend deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npx tsc --version
          npm run build
          ls
      
      - name: Test ssh connection 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /root/wwwroot/*
            mkdir -p /root/wwwroot
            scp -r out/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/wwwroot